### PR TITLE
New Pokedex

### PR DESCRIPTION
**Pull request by digita-LUNA**
Replaces Emerald's Pokedex with a custom one. Updated from the May PR.
CrystalDust-1
CrystalDust-7
CrystalDust-3
CrystalDust-4
CrystalDust-5
CrystalDust-8

### CODE REVIEW

**Comment by redsquidz** [comment]
Checked it out, looks awesome!! Love having a working map. Small bug (maybe?)... I was in goldenrod and saw koffing was off in the shadow lands, is this just on my end?

**Comment by digita-LUNA** [comment]
Please explain what you mean?

**Comment by redsquidz** [comment]
Koffing way out in the Pokemon League
https://user-images.githubusercontent.com/117706036/236689574-229259e4-e610-4d22-9b3d-77a8a19de120.png

**Comment by jamsilva** [comment]
> Koffing way out in the Pokemon League https://user-images.githubusercontent.com/117706036/236689574-229259e4-e610-4d22-9b3d-77a8a19de120.png

This code in `GetRegionMapGlowSectionIdAt` should have avoided that:
```
    else if (x == MAP_LEFTMOST_ROW || x >= MAP_RIGHTMOST_ROW)
        return MAPSEC_NONE;
```

Because I expect x to be 25 in this case (MAP_RIGHTMOST_ROW is 23) and the region to be REGION_JOHTO.
@MoriyaFaith, I think this would be the correct part of the code to look for a fix.

**Comment by jamsilva** [comment]
@MoriyaFaith actually, this can be fixed by changing the CreateAreaMarkerSprites function in pokedex_area_screen.c like so (I renamed MAP_*MOST_ROW to MAP_*MOST_COLUMN since the check is on the x coordinate - thus columns):
```C
static void CreateAreaMarkerSprites(void)
{
    u8 spriteId, currentRegion;
    static s16 x;
    static s16 y;
    static s16 i;
    static s16 mapSecId;
    static s16 numSprites;

    LoadSpriteSheet(&sAreaMarkerSpriteSheet);
    LoadSpritePalette(&sAreaMarkerSpritePalette);
    numSprites = 0;
    currentRegion = sPokedexAreaScreen->regionMap.currentRegion;
    for (i = 0; i < sPokedexAreaScreen->numSpecialAreas; i++)
    {
        mapSecId = sPokedexAreaScreen->specialAreaRegionMapSectionIds[i];
        x = gRegionMapEntries[mapSecId].x;

        if (x > MAP_RIGHTMOST_COLUMN || (x == MAP_LEFTMOST_COLUMN && currentRegion != REGION_KANTO))
            continue;

        x = 8 * (x + 4) + 4;
        y = 8 * (gRegionMapEntries[mapSecId].y) + 20;
        x += 4 * (gRegionMapEntries[mapSecId].width - 1);
        y += 4 * (gRegionMapEntries[mapSecId].height - 1);

        spriteId = CreateSprite(&sAreaMarkerSpriteTemplate, x, y, 0);
        if (spriteId != MAX_SPRITES)
        {
            gSprites[spriteId].invisible = TRUE;
            sPokedexAreaScreen->areaMarkerSprites[numSprites++] = &gSprites[spriteId];
        }
    }

    sPokedexAreaScreen->numAreaMarkerSprites = numSprites;
}
```

**Comment by Deokishisu** [comment]
Closing in favor of the more recent PR.

**Comment by digita-LUNA** [comment]
Closed due to #18

**Pull request closed without merging**
